call pathogen#infect()
call pathogen#helptags()
set showmatch
" Set the terminal font encoding
set encoding=utf-8
scriptencoding utf-8
set termencoding=utf-8

" ============ Source Settings Files ================
" ===================================================
source ~/.dotfiles/vim-files/plugin-settings/csapprox.vim
source ~/.dotfiles/vim-files/plugin-settings/appearance.vim
source ~/.dotfiles/vim-files/plugin-settings/indentGuides.vim
source ~/.dotfiles/vim-files/plugin-settings/lightline.vim
source ~/.dotfiles/vim-files/plugin-settings/delimitMate.vim
"source ~/.dotfiles/vim-files/elm-vim.vim
"source ~/.dotfiles/vim-files/plugin-settings/NERDTree.vim
source ~/.dotfiles/vim-files/plugin-settings/syntastic.vim
source ~/.dotfiles/vim-files/plugin-settings/vim-javascript.vim
source ~/.dotfiles/vim-files/plugin-settings/youCompleteMe.vim
"source ~/.dotfiles/vim-files/tagBar.vim
source ~/.dotfiles/vim-files/plugin-settings/javascriptLibrariesSyntax.vim
"source ~/.dotfiles/vim-files/minibufexpl.vim
source ~/.dotfiles/vim-files/plugin-settings/vim-golang.vim
"source ~/.dotfiles/vim-files/vim-haskell.vim
"source ~/.dotfiles/vim-files/rainbow-parens.vim
source ~/.dotfiles/vim-files/plugin-settings/emmet.vim



" =============== Plugin KeyBindings =================
" Emmet Trigger Leader -> Control + e then ,
" ================ General Config ====================

set number                      "Line numbers are good
set backspace=indent,eol,start  "Allow backspace in insert mode
set history=1000                "Store lots of :cmdline history
set showcmd                     "Show incomplete cmds down the bottom
set showmode                    "Show current mode down the bottom
set gcr=a:blinkon0              "Disable cursor blink
set visualbell                  "No sounds
set autoread                    "Reload files changed outside vim

set hidden

"turn on syntax highlighting
syntax on
filetype plugin indent on
let mapleader=","
" ================ Turn Off Swap Files ==============

set noswapfile
set nobackup
set nowb

" ================ Persistent Undo ==================
" Keep undo history across sessions, by storing in file.
" Only works all the time.
if has('persistent_undo') && !isdirectory(expand('~').'/dotfiles/vimfold/backups')
  silent !mkdir ~/dotfiles/vimfold/backups > /dev/null 2>&1
  set undodir=~/dotfiles/vimfold/backups
  set undofile
endif

" ================ Indentation ======================

set autoindent
set smartindent
set smarttab
set shiftwidth=4
set softtabstop=0
set tabstop=4
set expandtab
set textwidth=100


" Highlight the first column after the text width
"if exists('&colorcolumn')
   "set colorcolumn=+1
"endif



" Auto indent pasted text
nnoremap p p=`]<C-o>
nnoremap P P=`]<C-o>
"set pastetoggle=<F2>

set nowrap       "Don't wrap lines
set linebreak    "Wrap lines at convenient points

" ================ Folds ============================

"set foldmethod=indent   "fold based on indent
"set foldnestmax=3       "deepest fold is 3 levels
"set nofoldenable        "dont fold by default
"
"
" Fold with triple curly braces, fill with spaces
if has('folding')
    set foldenable
    set foldmethod=marker
    set foldopen=hor,search,tag,undo
    set fillchars=diff:\ ,fold:\ ,vert:\
endif

set nobackup
if has('writebackup')
    set nowritebackup
endif

" ================ Completion =======================

set wildmode=list:longest
"set wildmenu                "enable ctrl-n and ctrl-p to scroll thru matches
set wildignore=*.o,*.obj,*~ "stuff to ignore when tab completing
set wildignore+=*vim/backups*
set wildignore+=*sass-cache*
set wildignore+=*DS_Store*
set wildignore+=vendor/rails/**
set wildignore+=vendor/cache/**
set wildignore+=*.gem
set wildignore+=log/**
set wildignore+=tmp/**
set wildignore+=*.png,*.jpg,*.gif

" ================ Scrolling ========================

set scrolloff=8         "Start scrolling when we're 8 lines away from margins
set sidescrolloff=15
set sidescroll=1

" ================ Search ===========================

set incsearch       " Find the next match as we type the search
set hlsearch        " Highlight searches by default
set ignorecase      " Ignore case when searching...
set smartcase       " ...unless we type a capital

" ================ Custom Settings ========================
"
"




